#pragma once

#define SERIAL_PIO_USE_PIO1
#define MASTER_RIGHT
#define MATRIX_ROWS 8
#define MATRIX_COLS 7

#define MATRIX_ROW_PINS { GP26, GP27, GP28, GP29 }
#define MATRIX_COL_PINS { GP0, GP1, GP2, GP3, GP4, GP5, GP6 }
#define MATRIX_ROW_PINS_RIGHT { GP26, GP27, GP28, GP29 }
#define MATRIX_COL_PINS_RIGHT { GP0, GP1, GP2, GP3, GP4, GP5, GP6 }

#define DIODE_DIRECTION COL2ROW

#define SOFT_SERIAL_PIN GP7

// #define COMBO_VARIABLE_LEN
// #define COMBO_TERM 40
