#pragma once

#define SERIAL_PIO_USE_PIO1
#define MASTER_RIGHT
#define MATRIX_ROWS 10
#define MATRIX_COLS 7

#define MATRIX_ROW_PINS { GP0, GP1, GP2, GP3, GP4 }
#define MATRIX_COL_PINS { GP5, GP6, GP7, GP8, GP9, GP10, GP11 }
#define MATRIX_ROW_PINS_RIGHT { GP0, GP1, GP2, GP3, GP4 }
#define MATRIX_COL_PINS_RIGHT {  GP5, GP6, GP7, GP8, GP9, GP10, GP11 }

#define DIODE_DIRECTION COL2ROW

#define SOFT_SERIAL_PIN GP12

// #define SPLIT_USB_DETECT
// #define SPLIT_USB_TIMEOUT 2000
#define SPLIT_WATCHDOG_ENABLE
#define SPLIT_WATCHDOG_TIMEOUT 3000

// #define COMBO_VARIABLE_LEN
// #define COMBO_TERM 40
